<?php

namespace Plugins\BkpmUmkm\Exports;

use Illuminate\Support\Carbon;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Cell\DefaultValueBinder;
use Plugins\BkpmUmkm\Models\KbliModel;
use Plugins\BkpmUmkm\Models\SurveyModel;

class SurveyUmkmExport2020 extends DefaultValueBinder implements FromQuery, WithMapping, WithHeadings, WithCustomValueBinder, WithTitle
{
    use Exportable;

    protected $user;
    protected $status = '';
    protected $periode;

    public function __construct()
    {
        $this->user = auth()->user();
        if (request()->get('status')){
            $this->status = encrypt_decrypt(request()->get('status'));
        }
        $this->periode = (request()->has('periode') && filter(request()->input('periode')) != '' ? filter(request()->input('periode')) : \Carbon\Carbon::now()->format('Y'));
    }

    public function query()
    {
        // TODO: Implement query() method.
        $survey = SurveyModel::whereHas('umkm')->with(['umkm', 'umkm.provinsi', 'surveyor', 'survey_result'])->whereYear('surveys.created_at', $this->periode);
        if (!empty($this->status)){
            $survey->whereStatus($this->status);
        }
        switch ($this->user->group_id){
            case GROUP_SURVEYOR:
                $survey->where('surveys.surveyor_id', $this->user->id);
                break;
            case GROUP_QC_KORPROV:
                $survey->whereHas('surveyor', function ($q){
                    $q->where('users.id_provinsi', $this->user->id_provinsi);
                });
                break;
            case GROUP_QC_KORWIL:
            case GROUP_ASS_KORWIL:
            case GROUP_TA:
                $provinces = bkpmumkm_wilayah($this->user->id_provinsi);
                $survey->whereHas('surveyor', function ($q) use($provinces){
                    $provinces = ($provinces && isset($provinces['provinces']) ? $provinces['provinces'] : []);
                    $q->whereIn('users.id_provinsi', $provinces);
                });
                break;
            default:

                break;
        }
        return $survey;
    }

    public function bindValue(Cell $cell, $value)
    {
        if (is_numeric($value)) {
            $cell->setValueExplicit($value, DataType::TYPE_STRING);

            return true;
        }
        return parent::bindValue($cell, $value); // TODO: Change the autogenerated stub
    }

    public function map($row): array
    {
        $data = false;
        $surveyor = false;
        if ($row->survey_result) {
            $survey_result = $row->survey_result;
            $data = $survey_result->data;
            $surveyor = $row->surveyor;
        }
        if ($data){
            $responden = (isset($data['responden'])&&$data['responden'] ? $data['responden']: '');
            $profil_usaha    = (isset($data['profil_usaha'])&&$data['profil_usaha'] ? $data['profil_usaha'] : '');
            $profil_usaha_negara    = (isset($profil_usaha['negara'])&&!empty($profil_usaha['negara']) ? \SimpleCMS\Wilayah\Models\NegaraModel::select('kode_negara', 'nama_negara')->where('kode_negara', $profil_usaha['negara'])->first()->nama_negara : '');
            $profil_usaha_provinsi  = (isset($profil_usaha['provinsi'])&&!empty($profil_usaha['provinsi']) ? \SimpleCMS\Wilayah\Models\ProvinsiModel::select('kode_provinsi', 'nama_provinsi')->where('kode_provinsi', $profil_usaha['provinsi'])->first()->nama_provinsi : '');
            $profil_usaha_kabupaten = (isset($profil_usaha['kabupaten'])&&!empty($profil_usaha['kabupaten']) ? \SimpleCMS\Wilayah\Models\KabupatenModel::select('kode_kabupaten', 'nama_kabupaten')->where('kode_kabupaten', $profil_usaha['kabupaten'])->first()->nama_kabupaten : '');
            $profil_usaha_kecamatan = (isset($profil_usaha['kecamatan'])&&!empty($profil_usaha['kecamatan']) ? \SimpleCMS\Wilayah\Models\KecamatanModel::select('kode_kecamatan', 'nama_kecamatan')->where('kode_kecamatan', $profil_usaha['kecamatan'])->first()->nama_kecamatan : '');
            $profil_usaha_desa      = (isset($profil_usaha['desa'])&&!empty($profil_usaha['desa']) ? \SimpleCMS\Wilayah\Models\DesaModel::select('kode_desa', 'nama_desa')->where('kode_desa', $profil_usaha['desa'])->first()->nama_desa : '');
            $dokumentasi_profil_usaha_penghargaan    = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['penghargaan']) ? $data['dokumentasi_profil_usaha']['penghargaan'] : []);
            $dokumentasi_profil_usaha_penghargaan_files = '';
            foreach($dokumentasi_profil_usaha_penghargaan as $penghargaan){
                $dokumentasi_profil_usaha_penghargaan_files .= asset($penghargaan['file']) . "\n";
            }
            $dokumentasi_profil_usaha_sertifikasi_mutu    = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['sertifikasi']['mutu']) ? $data['dokumentasi_profil_usaha']['sertifikasi']['mutu'] : ['file'=>'']);
            $dokumentasi_profil_usaha_sertifikasi_halal  = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['sertifikasi']['halal']) ? $data['dokumentasi_profil_usaha']['sertifikasi']['halal'] : ['file'=>'']);
            $dokumentasi_profil_usaha_sertifikasi_lainya  = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['sertifikasi']['lainya']) ? $data['dokumentasi_profil_usaha']['sertifikasi']['lainya'] : []);
            $dokumentasi_profil_usaha_sertifikasi_lainya_files = '';
            foreach($dokumentasi_profil_usaha_sertifikasi_lainya as $lainya){
                $dokumentasi_profil_usaha_sertifikasi_lainya_files .= asset($lainya['file']) . "\n";
            }
            $dokumentasi_profil_usaha_legalitas_siup    = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['legalitas']['siup']) ? $data['dokumentasi_profil_usaha']['legalitas']['siup'] : ['file'=>'']);
            $dokumentasi_profil_usaha_legalitas_tdp  = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['legalitas']['tdp']) ? $data['dokumentasi_profil_usaha']['legalitas']['tdp'] : ['file'=>'']);
            $dokumentasi_profil_usaha_legalitas_npwp  = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['legalitas']['npwp']) ? $data['dokumentasi_profil_usaha']['legalitas']['npwp'] : ['file'=>'']);
            $dokumentasi_profil_usaha_legalitas_nib  = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['legalitas']['nib']) ? $data['dokumentasi_profil_usaha']['legalitas']['nib'] : ['file'=>'']);
            $dokumentasi_profil_usaha_legalitas_lainya  = (isset($data['dokumentasi_profil_usaha'])&&isset($data['dokumentasi_profil_usaha']['legalitas']['lainya']) ? $data['dokumentasi_profil_usaha']['legalitas']['lainya'] : []);
            $dokumentasi_profil_usaha_legalitas_lainya_files = '';
            foreach($dokumentasi_profil_usaha_legalitas_lainya as $lainya){
                $dokumentasi_profil_usaha_legalitas_lainya_files .= asset($lainya['file']) . "\n";
            }
            $profil_produk_jasa    = (isset($data['profil_produk_jasa'])&&$data['profil_produk_jasa'] ? $data['profil_produk_jasa'] : '');
            $profil_pengelolaan_usaha    = (isset($data['profil_pengelolaan_usaha'])&&$data['profil_pengelolaan_usaha'] ? $data['profil_pengelolaan_usaha'] : '');
            $jumlah_tenaga_kerja    = (isset($data['jumlah_tenaga_kerja'])&&$data['jumlah_tenaga_kerja'] ? $data['jumlah_tenaga_kerja'] : '');
            $jam_kerja_dalam_1_minggu    = (isset($data['jam_kerja_dalam_1_minggu']) ? $data['jam_kerja_dalam_1_minggu'] : '');
            $usia_tenaga_kerja    = (isset($data['usia_tenaga_kerja']) ? $data['usia_tenaga_kerja'] : '');
            $pendidikan_tenaga_kerja    = (isset($data['pendidikan_tenaga_kerja']) ? $data['pendidikan_tenaga_kerja'] : '');
            $struktur_organisasi    = (isset($data['struktur_organisasi']) ? $data['struktur_organisasi'] : '');
            $fasilitas_usaha    = (isset($data['fasilitas_usaha'])&&$data['fasilitas_usaha'] ? $data['fasilitas_usaha']: []);
            $fasilitas_usaha_jenis_kegiatan = '';
            $fasilitas_usaha_peralatan_mesin = '';
            $fasilitas_usaha_nilai = '';
            foreach($fasilitas_usaha as $fu){
                $fasilitas_usaha_jenis_kegiatan .= (isset($fu['jenis_kegiatan']) ? $fu['jenis_kegiatan'] : '') . ";\n";
                $fasilitas_usaha_peralatan_mesin .= (isset($fu['peralatan_mesin']) ? shortcodes($fu['peralatan_mesin']) : '') . ";";
                $fasilitas_usaha_nilai .= (isset($fu['nilai']) ? str_replace(['.', ','], '', $fu['nilai']) : '') . ";\n";
            }
            $assessment_kemitraan               = (isset($data['assessment_kemitraan'])&&$data['assessment_kemitraan'] ? $data['assessment_kemitraan']: []);
            $gambaran_umum                      = (isset($assessment_kemitraan['gambaran_umum'])?$assessment_kemitraan['gambaran_umum']:'');
            $prospektif_umkm_dengan_ub          = (isset($assessment_kemitraan['prospektif_umkm_dengan_ub'])?$assessment_kemitraan['prospektif_umkm_dengan_ub']:'');
            $kesesuaian_dalam_kemitraan         = (isset($assessment_kemitraan['kesesuaian_dalam_kemitraan'])?$assessment_kemitraan['kesesuaian_dalam_kemitraan']:'');
            $kapabilitas_dan_value_proposition  = (isset($assessment_kemitraan['kapabilitas_dan_value_proposition'])?$assessment_kemitraan['kapabilitas_dan_value_proposition']:'');
            $rencana_strategi = ( isset($gambaran_umum['rencana_strategi']) && is_array($gambaran_umum['rencana_strategi']) ? $gambaran_umum['rencana_strategi']:[]);
            $permasalahan_rantai_pasok_usaha = ( isset($gambaran_umum['permasalahan_rantai_pasok_usaha']) && is_array($gambaran_umum['permasalahan_rantai_pasok_usaha']) ? $gambaran_umum['permasalahan_rantai_pasok_usaha']:[]);
            $harapan_terhadap_perusahaan_mitra = ( isset($gambaran_umum['harapan_terhadap_perusahaan_mitra']) && is_array($gambaran_umum['harapan_terhadap_perusahaan_mitra']) ? $gambaran_umum['harapan_terhadap_perusahaan_mitra']:[]);
            $produk_jasa_dimiliki_umkm = ( isset($prospektif_umkm_dengan_ub['produk_jasa_dimiliki_umkm']) && is_array($prospektif_umkm_dengan_ub['produk_jasa_dimiliki_umkm']) ? $prospektif_umkm_dengan_ub['produk_jasa_dimiliki_umkm']:[]);
            $benefit_yang_ditawarkan = ( isset($prospektif_umkm_dengan_ub['benefit_yang_ditawarkan']) && is_array($prospektif_umkm_dengan_ub['benefit_yang_ditawarkan']) ? $prospektif_umkm_dengan_ub['benefit_yang_ditawarkan']:[]);
            $komitmen_dalam_kemitraan = ( isset($prospektif_umkm_dengan_ub['komitmen_dalam_kemitraan']) && is_array($prospektif_umkm_dengan_ub['komitmen_dalam_kemitraan']) ? $prospektif_umkm_dengan_ub['komitmen_dalam_kemitraan']:[]);
            $jenis_kemitraan_yang_diinginkan = ( isset($kesesuaian_dalam_kemitraan['jenis_kemitraan_yang_diinginkan']) && is_array($kesesuaian_dalam_kemitraan['jenis_kemitraan_yang_diinginkan']) ? $kesesuaian_dalam_kemitraan['jenis_kemitraan_yang_diinginkan']:[]);
            $jenis_ub_yang_akan_menjadi_mitra = ( isset($kesesuaian_dalam_kemitraan['jenis_ub_yang_akan_menjadi_mitra']) && is_array($kesesuaian_dalam_kemitraan['jenis_ub_yang_akan_menjadi_mitra']) ? $kesesuaian_dalam_kemitraan['jenis_ub_yang_akan_menjadi_mitra']:[]);
            $faktor_penunjang_kemitraan = ( isset($kesesuaian_dalam_kemitraan['faktor_penunjang_kemitraan']) && is_array($kesesuaian_dalam_kemitraan['faktor_penunjang_kemitraan']) ? $kesesuaian_dalam_kemitraan['faktor_penunjang_kemitraan']:[]);
            $kesiapan_organisasi = ( isset($kapabilitas_dan_value_proposition['kesiapan_organisasi']) && is_array($kapabilitas_dan_value_proposition['kesiapan_organisasi']) ? $kapabilitas_dan_value_proposition['kesiapan_organisasi']:[]);
            $keunggulan_usaha = ( isset($kapabilitas_dan_value_proposition['keunggulan_usaha']) && is_array($kapabilitas_dan_value_proposition['keunggulan_usaha']) ? $kapabilitas_dan_value_proposition['keunggulan_usaha']:[]);
            $manajemen_resiko = ( isset($kapabilitas_dan_value_proposition['manajemen_resiko']) && is_array($kapabilitas_dan_value_proposition['manajemen_resiko']) ? $kapabilitas_dan_value_proposition['manajemen_resiko']:[]);

            return [
                carbonParseTransFormat($survey_result->created_at, 'd/m/Y H:i'),
                (isset($responden['nama_responden']) ? $responden['nama_responden'] : ''),
                (isset($responden['jabatan']) ? $responden['jabatan'] : ''),
                (isset($responden['nomor_ponsel']) ? $responden['nomor_ponsel'] : ''),
                (isset($responden['email']) ? $responden['email'] : ''),
                $row->company_id,
                (isset($profil_usaha['nama_usaha']) ? $profil_usaha['nama_usaha'] : ''),
                (isset($profil_usaha['bentuk_badan_hukum']) ? $profil_usaha['bentuk_badan_hukum'] : ''),
                nl2br(isset($profil_usaha['deskripsi_usaha']) ? $profil_usaha['deskripsi_usaha'] : ''),
                (isset($profil_usaha['kepemilikan_nib_nomor']) ? $profil_usaha['kepemilikan_nib_nomor'] : ''),
                $profil_usaha_desa,
                $profil_usaha_kecamatan,
                $profil_usaha_kabupaten,
                $profil_usaha_provinsi,
                $profil_usaha_negara,
                nl2br(isset($profil_usaha['alamat']) ? $profil_usaha['alamat'] : ''),
                (isset($profil_usaha['kode_pos']) ? $profil_usaha['kode_pos'] : ''),
                (isset($profil_usaha['koordinat_gps_longitude']) ? $profil_usaha['koordinat_gps_longitude'] : ''),
                (isset($profil_usaha['koordinat_gps_latitude']) ? $profil_usaha['koordinat_gps_latitude'] : ''),
                (isset($profil_usaha['jumlah_kantor_cabang']) ? $profil_usaha['jumlah_kantor_cabang'] : ''),
                (isset($profil_usaha['telepon']) ? $profil_usaha['telepon'] . ";\n" : '') . (isset($profil_usaha['fax']) ? $profil_usaha['fax'] . ";\n" : '') . (isset($profil_usaha['ponsel']) ? $profil_usaha['ponsel'] . ";\n" : ''),
                (isset($profil_usaha['email']) ? $profil_usaha['email'] : ''),
                "Website: ". (isset($profil_usaha['website']) ? $profil_usaha['website'] : '-') ."\nFacebook: ". (isset($profil_usaha['facebook']) ? $profil_usaha['facebook'] : '-') ."\nInstagram: ". (isset($profil_usaha['instagram']) ? $profil_usaha['instagram'] : '-') ."\nTwitter: ". (isset($profil_usaha['twitter']) ? $profil_usaha['twitter'] : '-') ."\nLinkedIn: " . (isset($profil_usaha['linkedin']) ? $profil_usaha['linkedin'] : '-'),
                (isset($profil_usaha['nama_cp']) ? $profil_usaha['nama_cp'] : ''),
                (isset($profil_usaha['jabatan_cp']) ? $profil_usaha['jabatan_cp'] : ''),
                (isset($profil_usaha['telepon_cp']) ? $profil_usaha['telepon_cp'] . ";\n" : '').(isset($profil_usaha['fax_cp']) ? $profil_usaha['fax_cp'] . ";\n" : '').(isset($profil_usaha['ponsel_cp']) ? $profil_usaha['ponsel_cp'] . ";\n" : ''),
                (isset($profil_usaha['email_cp']) ? $profil_usaha['email_cp'] : ''),
                (isset($profil_usaha['modal_awal']) ? str_replace([',','.'], '', $profil_usaha['modal_awal']) : '0'),
                (isset($profil_usaha['rencana_investasi']) ? str_replace([',','.'], '', $profil_usaha['rencana_investasi']) : '0'),
                (isset($profil_usaha['realisasi_investasi']) ? str_replace([',','.'], '', $profil_usaha['realisasi_investasi']) : '0'),
                (isset($profil_usaha['keanggotaan_asosiasi']) ? $profil_usaha['keanggotaan_asosiasi'] : ''),
                $dokumentasi_profil_usaha_penghargaan_files,
                (!empty($dokumentasi_profil_usaha_sertifikasi_mutu['file']) ? asset($dokumentasi_profil_usaha_sertifikasi_mutu['file']) : ''),
                (!empty($dokumentasi_profil_usaha_sertifikasi_halal['file']) ? asset($dokumentasi_profil_usaha_sertifikasi_halal['file']) : ''),
                $dokumentasi_profil_usaha_sertifikasi_lainya_files,
                (!empty($dokumentasi_profil_usaha_legalitas_npwp['file']) ? asset($dokumentasi_profil_usaha_legalitas_npwp['file']) : ''),
                (!empty($dokumentasi_profil_usaha_legalitas_tdp['file']) ? asset($dokumentasi_profil_usaha_legalitas_tdp['file']) : ''),
                (!empty($dokumentasi_profil_usaha_legalitas_siup['file']) ? asset($dokumentasi_profil_usaha_legalitas_siup['file']) : ''),
                (!empty($dokumentasi_profil_usaha_legalitas_nib['file']) ? asset($dokumentasi_profil_usaha_legalitas_nib['file']) : ''),
                $dokumentasi_profil_usaha_legalitas_lainya_files,
                shortcodes((isset($profil_produk_jasa['merek'])?$profil_produk_jasa['merek']:'')),
                shortcodes((isset($profil_produk_jasa['jenis_dan_deskripsi'])?$profil_produk_jasa['jenis_dan_deskripsi']:'')),
                (isset($profil_pengelolaan_usaha['kepemilikan'])? $profil_pengelolaan_usaha['kepemilikan']:''),
                (isset($profil_pengelolaan_usaha['kepemilikan_lainya'])?$profil_pengelolaan_usaha['kepemilikan_lainya']:''),
                (isset($profil_pengelolaan_usaha['tahun_berdiri'])?$profil_pengelolaan_usaha['tahun_berdiri']:''),
                (isset($profil_pengelolaan_usaha['usia'])?$profil_pengelolaan_usaha['usia']:''),
                (isset($profil_pengelolaan_usaha['omzet']) ? $profil_pengelolaan_usaha['omzet']:''),
                (isset($profil_pengelolaan_usaha['omzet_sebutkan'])?$profil_pengelolaan_usaha['omzet_sebutkan']:''),
                (isset($jumlah_tenaga_kerja['operasional']['pria']) ? $jumlah_tenaga_kerja['operasional']['pria'] : '0'),
                (isset($jumlah_tenaga_kerja['operasional']['wanita']) ? $jumlah_tenaga_kerja['operasional']['wanita'] : '0'),
                (isset($jumlah_tenaga_kerja['pendukung']['pria']) ? $jumlah_tenaga_kerja['pendukung']['pria'] : '0'),
                (isset($jumlah_tenaga_kerja['pendukung']['wanita']) ? $jumlah_tenaga_kerja['pendukung']['wanita'] : '0'),
                (isset($jam_kerja_dalam_1_minggu['operasional']['pria']) ? $jam_kerja_dalam_1_minggu['operasional']['pria'] : '0'),
                (isset($jam_kerja_dalam_1_minggu['operasional']['wanita']) ? $jam_kerja_dalam_1_minggu['operasional']['wanita'] : '0'),
                (isset($jam_kerja_dalam_1_minggu['pendukung']['pria']) ? $jam_kerja_dalam_1_minggu['pendukung']['pria'] : '0'),
                (isset($jam_kerja_dalam_1_minggu['pendukung']['wanita']) ? $jam_kerja_dalam_1_minggu['pendukung']['wanita'] : '0'),
                (isset($jumlah_tenaga_kerja['jumlah_tk']['pria']) ? $jumlah_tenaga_kerja['jumlah_tk']['pria'] : '0'),
                (isset($jumlah_tenaga_kerja['jumlah_tk']['wanita']) ? $jumlah_tenaga_kerja['jumlah_tk']['wanita'] : '0'),
                (isset($usia_tenaga_kerja['usia_kurang_samadengan_25']['pria'])?$usia_tenaga_kerja['usia_kurang_samadengan_25']['pria']:'0'),
                (isset($usia_tenaga_kerja['usia_kurang_samadengan_25']['wanita'])?$usia_tenaga_kerja['usia_kurang_samadengan_25']['wanita']:'0'),
                (isset($usia_tenaga_kerja["usia_26_sampai_35"]['pria'])?$usia_tenaga_kerja["usia_26_sampai_35"]['pria']:'0'),
                (isset($usia_tenaga_kerja["usia_26_sampai_35"]['wanita'])?$usia_tenaga_kerja["usia_26_sampai_35"]['wanita']:'0'),
                (isset($usia_tenaga_kerja["usia_36_sampai_45"]['pria'])?$usia_tenaga_kerja["usia_36_sampai_45"]['pria']:'0'),
                (isset($usia_tenaga_kerja["usia_36_sampai_45"]['wanita'])?$usia_tenaga_kerja["usia_36_sampai_45"]['wanita']:'0'),
                (isset($usia_tenaga_kerja["usia_46_sampai_55"]['pria'])?$usia_tenaga_kerja["usia_46_sampai_55"]['pria']:'0'),
                (isset($usia_tenaga_kerja["usia_46_sampai_55"]['wanita'])?$usia_tenaga_kerja["usia_46_sampai_55"]['wanita']:'0'),
                (isset($usia_tenaga_kerja['usia_lebihdari_65']['pria'])?$usia_tenaga_kerja['usia_lebihdari_65']['pria']:'0'),
                (isset($usia_tenaga_kerja['usia_lebihdari_65']['wanita'])?$usia_tenaga_kerja['usia_lebihdari_65']['wanita']:'0'),
                (isset($pendidikan_tenaga_kerja['sd']['pria'])?$pendidikan_tenaga_kerja['sd']['pria']:'0'),
                (isset($pendidikan_tenaga_kerja['sd']['wanita'])?$pendidikan_tenaga_kerja['sd']['wanita']:'0'),
                (isset($pendidikan_tenaga_kerja['smp']['pria'])?$pendidikan_tenaga_kerja['smp']['pria']:'0'),
                (isset($pendidikan_tenaga_kerja['smp']['wanita'])?$pendidikan_tenaga_kerja['smp']['wanita']:'0'),
                (isset($pendidikan_tenaga_kerja['sma_smk']['pria'])?$pendidikan_tenaga_kerja['sma_smk']['pria']:'0'),
                (isset($pendidikan_tenaga_kerja['sma_smk']['wanita'])?$pendidikan_tenaga_kerja['sma_smk']['wanita']:'0'),
                (isset($pendidikan_tenaga_kerja['diploma']['pria'])?$pendidikan_tenaga_kerja['diploma']['pria']:'0'),
                (isset($pendidikan_tenaga_kerja['diploma']['wanita'])?$pendidikan_tenaga_kerja['diploma']['wanita']:'0'),
                (isset($pendidikan_tenaga_kerja['s1']['pria'])?$pendidikan_tenaga_kerja['s1']['pria']:'0'),
                (isset($pendidikan_tenaga_kerja['s1']['wanita'])?$pendidikan_tenaga_kerja['s1']['wanita']:'0'),
                (isset($pendidikan_tenaga_kerja['s2_s3']['pria'])?$pendidikan_tenaga_kerja['s2_s3']['pria']:'0'),
                (isset($pendidikan_tenaga_kerja['s2_s3']['wanita'])?$pendidikan_tenaga_kerja['s2_s3']['wanita']:'0'),
                shortcodes((isset($struktur_organisasi['deskripsi'])?$struktur_organisasi['deskripsi']:'')),
                $fasilitas_usaha_jenis_kegiatan,
                $fasilitas_usaha_peralatan_mesin,
                $fasilitas_usaha_nilai,

                shortcodes((isset($gambaran_umum['visi'])?$gambaran_umum['visi']:'-')),
                shortcodes((isset($gambaran_umum['misi'])?$gambaran_umum['misi']:'-')),

                (in_array('Pengembangan Pasar', $rencana_strategi) ? 'Pengembangan Pasar':''),
                (in_array('Anekaragaman Bentuk/Variasi Produk', $rencana_strategi) ? 'Anekaragaman Bentuk/Variasi Produk':''),
                (in_array('Menekan Biaya Produksi/Penghematan', $rencana_strategi) ? 'Menekan Biaya Produksi/Penghematan':''),
                (in_array('Membutuhkan Kemitraan', $rencana_strategi) ? 'Membutuhkan Kemitraan':''),
                shortcodes((isset($gambaran_umum['rencana_strategi_lainya'])?$gambaran_umum['rencana_strategi_lainya']:'')),
                (in_array('Sulitnya pasokan bahan baku', $permasalahan_rantai_pasok_usaha) ? 'Sulitnya pasokan bahan baku':''),
                (in_array('Kesulitan Pemasaran Produk', $permasalahan_rantai_pasok_usaha) ? 'Kesulitan Pemasaran Produk':''),
                (in_array('Keterbatasan Persediaan', $permasalahan_rantai_pasok_usaha) ? 'Keterbatasan Persediaan':''),
                shortcodes((isset($gambaran_umum['permasalahan_rantai_pasok_usaha_lainya'])?$gambaran_umum['permasalahan_rantai_pasok_usaha_lainya']:'')),
                (in_array('Membantu dalam pemasaran produk', $harapan_terhadap_perusahaan_mitra) ? 'Membantu dalam pemasaran produk':''),
                (in_array('Bantuan dalam bentuk permodalan', $harapan_terhadap_perusahaan_mitra) ? 'Bantuan dalam bentuk permodalan':''),
                (in_array('Menerima order terhadap produk/jasa', $harapan_terhadap_perusahaan_mitra) ? 'Menerima order terhadap produk/jasa':''),
                shortcodes((isset($gambaran_umum['harapan_terhadap_perusahaan_mitra_lainya'])?$gambaran_umum['harapan_terhadap_perusahaan_mitra_lainya']:'')),
                (in_array('Telah memenuhi standar kualitas', $produk_jasa_dimiliki_umkm) ? 'Telah memenuhi standar kualitas':''),
                (in_array('Memiliki kualitas yang baik', $produk_jasa_dimiliki_umkm) ? 'Memiliki kualitas yang baik':''),
                (in_array('Permintaannya cukup tinggi', $produk_jasa_dimiliki_umkm) ? 'Permintaannya cukup tinggi':''),
                shortcodes((isset($prospektif_umkm_dengan_ub['produk_jasa_dimiliki_umkm_lainya'])?$prospektif_umkm_dengan_ub['produk_jasa_dimiliki_umkm_lainya']:'')),
                (in_array('Pengiriman produk/jasa tepat waktu', $benefit_yang_ditawarkan) ? 'Pengiriman produk/jasa tepat waktu':''),
                (in_array('Adanya garansi atas pelayanan', $benefit_yang_ditawarkan) ? 'Adanya garansi atas pelayanan':''),
                (in_array('Memiliki Dukungan Pemerintah', $benefit_yang_ditawarkan) ? 'Memiliki Dukungan Pemerintah':''),
                (in_array('Jaminan Keamanan sosial', $benefit_yang_ditawarkan) ? 'Jaminan Keamanan sosial':''),
                shortcodes((isset($prospektif_umkm_dengan_ub['benefit_yang_ditawarkan_lainya'])?$prospektif_umkm_dengan_ub['benefit_yang_ditawarkan_lainya']:'')),
                (in_array('Legalitas Usaha yang Sah', $komitmen_dalam_kemitraan) ? 'Legalitas Usaha yang Sah':''),
                (in_array('Sudah berpengalaman dalam usaha', $komitmen_dalam_kemitraan) ? 'Sudah berpengalaman dalam usaha':''),
                (in_array('Keberadaaan lokasi usaha yang jelas', $komitmen_dalam_kemitraan) ? 'Keberadaaan lokasi usaha yang jelas':''),
                (in_array('Ada dalam pengawasan Pemerintah', $komitmen_dalam_kemitraan) ? 'Ada dalam pengawasan Pemerintah':''),
                (in_array('Mempunyai permodalan yang memadai', $komitmen_dalam_kemitraan) ? 'Mempunyai permodalan yang memadai':''),
                (in_array('Sumber daya manusia yang kompeten', $komitmen_dalam_kemitraan) ? 'Sumber daya manusia yang kompeten':''),
                shortcodes((isset($prospektif_umkm_dengan_ub['komitmen_dalam_kemitraan_lainya'])?$prospektif_umkm_dengan_ub['komitmen_dalam_kemitraan_lainya']:'')),
                (in_array('Subkontrak', $jenis_kemitraan_yang_diinginkan) ? 'Subkontrak':''),
                (in_array('Keagenan', $jenis_kemitraan_yang_diinginkan) ? 'Keagenan':''),
                (in_array('Waralaba', $jenis_kemitraan_yang_diinginkan) ? 'Waralaba':''),
                (in_array('Inti-plasma', $jenis_kemitraan_yang_diinginkan) ? 'Inti-plasma':''),
                (in_array('Perdagangan umum', $jenis_kemitraan_yang_diinginkan) ? 'Perdagangan umum':''),
                shortcodes((isset($kesesuaian_dalam_kemitraan['jenis_kemitraan_yang_diinginkan_lainya'])?$kesesuaian_dalam_kemitraan['jenis_kemitraan_yang_diinginkan_lainya']:'')),
                (in_array('Perusahaan Jasa Besar', $jenis_ub_yang_akan_menjadi_mitra) ? 'Perusahaan Jasa Besar':''),
                (in_array('Perusahaan Manufaktur', $jenis_ub_yang_akan_menjadi_mitra) ? 'Perusahaan Manufaktur':''),
                (in_array('Modern Reseller', $jenis_ub_yang_akan_menjadi_mitra) ? 'Modern Reseller':''),
                (in_array('Online Marketplace', $jenis_ub_yang_akan_menjadi_mitra) ? 'Online Marketplace':''),
                (in_array('Perhotelan dan Pariwisata', $jenis_ub_yang_akan_menjadi_mitra) ? 'Perhotelan dan Pariwisata':''),
                (in_array('Konstruksi', $jenis_ub_yang_akan_menjadi_mitra) ? 'Konstruksi':''),
                (in_array('Perkantoran', $jenis_ub_yang_akan_menjadi_mitra) ? 'Perkantoran':''),
                shortcodes((isset($kesesuaian_dalam_kemitraan['jenis_ub_yang_akan_menjadi_mitra_lainya'])?$kesesuaian_dalam_kemitraan['jenis_ub_yang_akan_menjadi_mitra_lainya']:'')),
                (in_array('Masih dalam 1 provinsi', $faktor_penunjang_kemitraan) ? 'Masih dalam 1 provinsi':''),
                (in_array('Masih dalam 1 kota/kabupaten', $faktor_penunjang_kemitraan) ? 'Masih dalam 1 kota/kabupaten':''),
                (in_array('Akses UMKM mudah ditempuh', $faktor_penunjang_kemitraan) ? 'Akses UMKM mudah ditempuh':''),
                shortcodes((isset($kesesuaian_dalam_kemitraan['faktor_penunjang_kemitraan_lainya'])?$kesesuaian_dalam_kemitraan['faktor_penunjang_kemitraan_lainya']:'')),
                (in_array('Pengalaman Kemitraan dengan beberapa Usaha Besar', $kesiapan_organisasi) ? 'Pengalaman Kemitraan dengan beberapa Usaha Besar':''),
                (in_array('Pemilik UMKM sudah punya wawasan kemitraan', $kesiapan_organisasi) ? 'Pemilik UMKM sudah punya wawasan kemitraan':''),
                (in_array('Kondisi Keuangan yang baik (modal kerja sendiri,cash flow, hutang yang rendah)', $kesiapan_organisasi) ? 'Kondisi Keuangan yang baik (modal kerja sendiri,cash flow, hutang yang rendah)':''),
                shortcodes((isset($kapabilitas_dan_value_proposition['kesiapan_organisasi_lainya'])?$kapabilitas_dan_value_proposition['kesiapan_organisasi_lainya']:'')),
                (in_array('Memiliki Standarisasi Produk', $keunggulan_usaha) ? 'Memiliki Standarisasi Produk':''),
                (in_array('Pengalaman Ekspor', $keunggulan_usaha) ? 'Pengalaman Ekspor':''),
                (in_array('Mempunyai Penghargaan (Award)', $keunggulan_usaha) ? 'Mempunyai Penghargaan (Award)':''),
                (in_array('Tenaga kerja mempunyai sertifikasi keahlian', $keunggulan_usaha) ? 'Tenaga kerja mempunyai sertifikasi keahlian':''),
                shortcodes((isset($kapabilitas_dan_value_proposition['keunggulan_usaha_lainya'])?$kapabilitas_dan_value_proposition['keunggulan_usaha_lainya']:'')),
                (in_array('Mempunyai standar keselamatan dan kesehatan kerja (Peralatan Apar, Kotak P3K, dll.)', $manajemen_resiko) ? 'Mempunyai standar keselamatan dan kesehatan kerja (Peralatan Apar, Kotak P3K, dll.)':''),
                (in_array('Memiliki asuransi usaha (BPJS, Ketenagakerjaan, kerusakan, bencana, kematian)', $manajemen_resiko) ? 'Memiliki asuransi usaha (BPJS, Ketenagakerjaan, kerusakan, bencana, kematian)':''),
                (in_array('Memiliki Tabungan Deposito dan emas di bank', $manajemen_resiko) ? 'Memiliki Tabungan Deposito dan emas di bank':''),
                (in_array('Memiliki aset atas nama sendiri (SHM rumah, lahan, kendaraan)', $manajemen_resiko) ? 'Memiliki aset atas nama sendiri (SHM rumah, lahan, kendaraan)':''),
                (in_array('Memiliki sistem perekrutan yang baik', $manajemen_resiko) ? 'Memiliki sistem perekrutan yang baik':''),
                shortcodes((isset($kapabilitas_dan_value_proposition['manajemen_resiko_lainya'])?$kapabilitas_dan_value_proposition['manajemen_resiko_lainya']:'')),
                (isset($responden['dibuat_di']) ? $responden['dibuat_di'] : ''),
                (isset($responden['tanggal']) ? carbonParseTransFormat($responden['tanggal'], 'd-m-Y') : ''),
                trans("label.survey_status_{$row->status}"),
                ($surveyor ? $surveyor->name : ''),
                ($surveyor ? $surveyor->email : ''),
                ($surveyor ? $surveyor->mobile_phone : ''),
                ($surveyor&&$surveyor->provinsi ? $surveyor->provinsi->nama_provinsi : ''),
                ($surveyor&&$surveyor->kabupaten ? $surveyor->kabupaten->nama_kabupaten : ''),
                ($surveyor&&$surveyor->kecamatan ? $surveyor->kecamatan->nama_kecamatan : ''),
                ($surveyor&&$surveyor->desa ? $surveyor->desa->nama_desa : ''),
                ($surveyor ? $surveyor->address : '')
            ];
        }else{
            return [
                '',
                '',
                '',
                '',
                '',
                $row->company_id,
                $row->umkm->name,
                '',
                '',
                $row->umkm->nib,
                ($row->umkm->desa ? $row->umkm->desa->nama_desa : ''),
                ($row->umkm->kecamatan ? $row->umkm->kecamatan->nama_kecamatan : ''),
                ($row->umkm->kabupaten ? $row->umkm->kabupaten->nama_kabupaten : ''),
                ($row->umkm->provinsi ? $row->umkm->provinsi->nama_provinsi : ''),
                ($row->umkm->negara ? $row->umkm->negara->nama_negara : ''),
                nl2br($row->umkm->address),
                $row->umkm->postal_code,
                $row->umkm->longitude,
                $row->umkm->latitude,
                ($row->umkm->telp ? $row->umkm->telp . ";\n" : '') . ($row->umkm->fax ? $row->umkm->fax . ";\n" : ''),
                $row->umkm->email,
                '',
                '',
                '',
                '',
                '0',
                '0',
                '0',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',

                '',
                '',

                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                trans("label.survey_status_{$row->status}"),
                ($surveyor ? $surveyor->name : ''),
                ($surveyor ? $surveyor->email : ''),
                ($surveyor ? $surveyor->mobile_phone : ''),
                ($surveyor&&$surveyor->provinsi ? $surveyor->provinsi->nama_provinsi : ''),
                ($surveyor&&$surveyor->kabupaten ? $surveyor->kabupaten->nama_kabupaten : ''),
                ($surveyor&&$surveyor->kecamatan ? $surveyor->kecamatan->nama_kecamatan : ''),
                ($surveyor&&$surveyor->desa ? $surveyor->desa->nama_desa : ''),
                ($surveyor ? $surveyor->address : '')
            ];
        }
    }

    public function headings(): array
    {
        // TODO: Implement headings() method.
        return [
            "Waktu Survey (Tgl/Bulan/Thn; Jam)", //done
            "Nama Responden", //done
            "Jabatan", //done
            "Nomor Ponsel Responden", //done
            "Email Responden", //done
            "ProfilUsaha_ID", //done
            "Nama Usaha", //done
            "Bentuk Badan Hukum", //done
            "Deskripsi Usaha", //done
            "NIB (Nomor Induk Berusaha)", //done
            "Alamat Usaha_Kelurahan", //done
            "Alamat Usaha_Kecamatan", //done
            "Alamat Usaha_Kabupaten/Kota", //done
            "Alamat Usaha_Provinsi", //done
            "Alamat Usaha_Negara", //done
            "Alamat Usaha", //done
            "Alamat Usaha_Kode Pos", //done
            "Alamat Usaha_Koordinat GPS Longitude lokasi Proyek", //done
            "Alamat Usaha_Koordinat GPS Latitude lokasi Proyek", //done
            "Nomor Telepon/fax/ponsel Perusahaan", //done
            "Email Perusahaan", //done
            "Akun Media Sosial/ Website Perusahaan", //done
            "ContactPerson", //done
            "Nomor Telepon/Fax/ Ponsel Contact Person", //done
            "Email Contact Person", //done
            "Modal Awal", //done
            "Rencana Investasi", //done
            "Realisasi Investasi", //done
            "KeanggotaanAsosiasi", //done
            "Penghargaan", //done
            "Sertifikasi Mutu", //done
            "Sertifikasi Halal", //done
            "Sertifikasi Lainnya", //done
            "Legalitas_NPWP", //done
            "Legalitas_TDP", //done
            "Legalitas_SIUP", //done
            "Legalitas_NIB", //done
            "LegalitasLainnya", //done
            "Merk Produk/Jasa", //done
            "Jenis & Deskripsi Produk/Jasa", //done
            "PengelolaanUsaha", //done
            "PengelolaanUsahaLainnya", //done
            "TahunPendirianUsaha", //done
            "Usia (thn)", //done
            "OmzetPertahun", //done
            "Sebutkan Jika omzet ≤ Rp. 300 juta", //done
            "JumlahTenagaKerjaOperasionalPria", //done
            "JumlahTenagaKerjaOperasionalWanita", //done
            "JumlahTenagaKerjaPendukungPria", //done
            "JumlahTenagaKerjaPendukungWanita", //done
            "JamKerjaTenagaKerjaOperasionalPria", //done
            "JamKerjaTenagaKerjaOperasionalWanita", //done
            "JamKerjaTenagaKerjaPendukungPria", //done
            "JamKerjaTenagaKerjaPendukungWanita", //done
            "Jumlah TK_Pria", //done
            "Jumlah TK_Wanita", //done
            "Usia TK ≤ 25 Pria", //done
            "Usia TK ≤ 25 Wanita", //done
            "Usia TK 26-35 Pria", //done
            "Usia TK 26-35 Wanita", //done
            "Usia TK 36-45 Pria", //done
            "Usia TK 36-45 Wanita", //done
            "Usia TK 46-55 Pria", //done
            "Usia TK 46-55 Wanita", //done
            "Usia TK > 65 Pria", //done
            "Usia TK >65 Wanita", //done
            "SD Pria", //done
            "SD Wanita", //done
            "SMP Pria", //done
            "SMP Wanita", //done
            "SMA Pria", //done
            "SMA Wanita", //done
            "Diploma Pria", //done
            "Diploma Wanita", //done
            "S1 Pria", //done
            "S1 Wanita", //done
            "S2-S3 Pria", //done
            "S2-S3 Wanita", //done
            "Path Image Struktur Organisasi", //done
            "JenisKegiatan", //done
            "Peralatan/Mesin", //done
            "NilaiPerkiraan", //done
            "Visi Pengembangan Usaha (a)",
            "Misi Pengembangan Usaha (b)",
            "Rencana Strategi Pengembangan Usaha (a)",
            "Rencana Strategi Pengembangan Usaha (b)",
            "Rencana Strategi Pengembangan Usaha (c)",
            "Rencana Strategi Pengembangan Usaha (d)",
            "Rencana Strategi Pengembangan Usaha (e)",
            "Permasalahan Rantai Pasok Usaha (a)",
            "Permasalahan Rantai Pasok Usaha (b)",
            "Permasalahan Rantai Pasok Usaha (c)",
            "Permasalahan Rantai Pasok Usaha (d)",
            "Harapan terhadap Perusahaan Mitra (a)",
            "Harapan terhadap Perusahaan Mitra (b)",
            "Harapan terhadap Perusahaan Mitra (c)",
            "Harapan terhadap Perusahaan Mitra (d)",
            "Produk/Jasa yang dimiliki UMKM (a)",
            "Produk/Jasa yang dimiliki UMKM (b)",
            "Produk/Jasa yang dimiliki UMKM (c)",
            "Produk/Jasa yang dimiliki UMKM (d)",
            "Benefit yang ditawarkan (a)",
            "Benefit yang ditawarkan (b)",
            "Benefit yang ditawarkan (c)",
            "Benefit yang ditawarkan (d)",
            "Benefit yang ditawarkan (e)",
            "Komitmen dalam kemitraan (a)",
            "Komitmen dalam kemitraan (b)",
            "Komitmen dalam kemitraan (c)",
            "Komitmen dalam kemitraan (d)",
            "Komitmen dalam kemitraan (e)",
            "Komitmen dalam kemitraan (f)",
            "Komitmen dalam kemitraan (g)",
            "Jenis Kemitraan yang diinginkan (a)",
            "Jenis Kemitraan yang diinginkan (b)",
            "Jenis Kemitraan yang diinginkan (c)",
            "Jenis Kemitraan yang diinginkan (d)",
            "Jenis Kemitraan yang diinginkan (e)",
            "Jenis Kemitraan yang diinginkan (f)",
            "Jenis Usaha Besar yang akan menjadi mitra (a)",
            "Jenis Usaha Besar yang akan menjadi mitra (b)",
            "Jenis Usaha Besar yang akan menjadi mitra (c)",
            "Jenis Usaha Besar yang akan menjadi mitra (d)",
            "Jenis Usaha Besar yang akan menjadi mitra (e)",
            "Jenis Usaha Besar yang akan menjadi mitra (f)",
            "Jenis Usaha Besar yang akan menjadi mitra (g)",
            "Jenis Usaha Besar yang akan menjadi mitra (h)",
            "Faktor Penunjang Kemitraan (a)",
            "Faktor Penunjang Kemitraan (b)",
            "Faktor Penunjang Kemitraan (c)",
            "Faktor Penunjang Kemitraan (d)",
            "Kesiapan Organisasi (a)",
            "Kesiapan Organisasi (b)",
            "Kesiapan Organisasi (c)",
            "Kesiapan Organisasi (d)",
            "Keunggulan Usaha (a)",
            "Keunggulan Usaha (b)",
            "Keunggulan Usaha (c)",
            "Keunggulan Usaha (d)",
            "Keunggulan Usaha (e)",
            "Manajemen Resiko (a)",
            "Manajemen Resiko (b)",
            "Manajemen Resiko (c)",
            "Manajemen Resiko (d)",
            "Manajemen Resiko (e)",
            "Manajemen Resiko (f)",
            "DIBUAT DI",
            "TANGGAL",
            trans('label.status'),
            'Nama Surveyor',
            'Email Surveyor',
            'Phone Surveyor',
            'Provinsi Surveyor',
            'Kabupaten Surveyor',
            'Kecamatan Surveyor',
            'Desa Surveyor',
            'Alamat Surveyor',
        ];
    }

    public function title(): string
    {
        // TODO: Implement title() method.
        return "Survey-UMKM-" . Carbon::now()->format('dmYHis');
    }
}
