INSERT INTO provinsi (kode_provinsi, nama_provinsi, hc_key) VALUES
('11', 'ACEH', 'id-ac'),
('12', 'SUMATERA UTARA', 'id-su'),
('13', 'SUMATERA BARAT', 'id-sb'),
('14', 'RIAU', 'id-ri'),
('15', 'JAMBI', 'id-ja'),
('16', 'SUMATERA SELATAN', 'id-sl'),
('17', 'BENGKULU', 'id-be'),
('18', 'LAMPUNG', 'id-1024'),
('19', 'BABEL', 'id-bb'),
('21', 'KEPULAUAN RIAU', 'id-kr'),
('31', 'DKI JAKARTA', 'id-jk'),
('32', 'JAWA BARAT', 'id-jr'),
('33', 'JAWA TENGAH', 'id-jt'),
('34', 'DAERAH ISTIMEWA YOGYAKARTA', 'id-yo'),
('35', 'JAWA TIMUR', 'id-ji'),
('36', 'BANTEN', 'id-bt'),
('51', 'BALI', 'id-ba'),
('52', 'NUSA TENGGARA BARAT', 'id-nb'),
('53', 'NUSA TENGGARA TIMUR', 'id-nt'),
('61', 'KALIMANTAN BARAT', 'id-kb'),
('62', 'KALIMANTAN TENGAH', 'id-kt'),
('63', 'KALIMANTAN SELATAN', 'id-ks'),
('64', 'KALIMANTAN TIMUR', 'id-ki'),
('65', 'KALIMANTAN UTARA', 'id-ku'),
('71', 'SULAWESI UTARA', 'id-sw'),
('72', 'SULAWESI TENGAH', 'id-st'),
('73', 'SULAWESI SELATAN', 'id-se'),
('74', 'SULAWESI TENGGARA', 'id-sg'),
('75', 'GORONTALO', 'id-go'),
('76', 'SULAWESI BARAT', 'id-sr'),
('81', 'MALUKU', 'id-ma'),
('82', 'MALUKU UTARA', 'id-la'),
('91', 'P A P U A', 'id-pa'),
('92', 'PAPUA BARAT', 'id-ib');